// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqYP3XgWSVRFNoois9aUi96ADd-luv6Ls',
    appId: '1:627549356878:android:cafc5aa32d32d78e33541f',
    messagingSenderId: '627549356878',
    projectId: 'blindspot-18dd0',
    storageBucket: 'blindspot-18dd0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3qXTqJPhRpItUkagIbVYfvap7U58UpU4',
    appId: '1:627549356878:ios:0da798b52effa18733541f',
    messagingSenderId: '627549356878',
    projectId: 'blindspot-18dd0',
    storageBucket: 'blindspot-18dd0.appspot.com',
    iosClientId: '627549356878-v6gthdg1948qlderq5i6stgu9jjgvcba.apps.googleusercontent.com',
    iosBundleId: 'com.blindspot.blindspot',
  );
}
